// GitHub-only projects (repo link, no live page, no screenshot of their own)
// show the repo's social card instead of the placeholder — generated by
// GitHub at opengraph.githubassets.com, so it stays current with the repo.
const PLACEHOLDER = '/resources/default.jpg';

const githubRepoPath = (url) => url?.match(/github\.com\/([^/]+\/[^/#?]+)/)?.[1];

// Returns the social-card URL when the rule applies, else null.
export const githubCardImage = (project) => {
  const own = project.image ?? project.images?.[0];
  const repo = githubRepoPath(project.github);
  if (repo && !project.liveDemo && (!own || own === PLACEHOLDER)) {
    return `https://opengraph.githubassets.com/1/${repo}`;
  }
  return null;
};
